[package]
name = "disable-enhance-pointer-precision-automatically"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winsafe = { version = "0.0.20", features = ["kernel", "user"] }
sysinfo = "0.30"
